<a href="https://colab.research.google.com/github/rnterrors404/external/blob/main/linear%20algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import numpy.linalg as lp

a = np.array([[1,2,3,4],
                    [5,6,7,8]])

b = np.array([[9,0,1,2],
                    [3,4,7,8]])

# addition
c = a+b
print("addition")
print(c)
print()

# subtraction
d = a- b
print("subtraction")
print(d)
print()

# multiplication
a1 = np.array([[1,2],[3,4]])
b1 = np.array([[5,6],[7,8]])
m = np.dot(a1,b1)
print('multiplication')
print(m)
print()

# transpose
t = np.transpose(a)
print('transpose')
print(t)
print()

# determinat
e = lp.det(b1)
print('determinant')
print(e)
print()

# inverse
i = lp.inv(a1)
print("inverse")
print(i)
print()

# eigen
g = lp.eig(a1)
print("eigen")
print(g)
print()

addition
[[10  2  4  6]
 [ 8 10 14 16]]

subtraction
[[-8  2  2  2]
 [ 2  2  0  0]]

multiplication
[[19 22]
 [43 50]]

transpose
[[1 5]
 [2 6]
 [3 7]
 [4 8]]

determinant
-2.000000000000005

inverse
[[-2.   1. ]
 [ 1.5 -0.5]]

eigen
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

